kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: echoserver
subjects:
- kind: ServiceAccount
  name: echoserver
roleRef:
  kind: Role
  name: echoserver
  apiGroup: rbac.authorization.k8s.io
